/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Base64: typeof import('./../components/tools/convert/module/base64.vue')['default']
    Bookmark: typeof import('./../components/Bookmark.vue')['default']
    Color: typeof import('./../components/tools/generate/module/color.vue')['default']
    Convert: typeof import('./../components/tools/convert/index.vue')['default']
    Expand: typeof import('./../components/Expand.vue')['default']
    FullScreen: typeof import('./../components/FullScreen.vue')['default']
    Generate: typeof import('./../components/tools/generate/index.vue')['default']
    Hash: typeof import('./../components/tools/convert/module/hash.vue')['default']
    Logo: typeof import('./../components/Logo.vue')['default']
    Math: typeof import('./../components/tools/convert/module/math.vue')['default']
    Search: typeof import('./../components/Search.vue')['default']
    SharedSubtitle: typeof import('./../components/SharedSubtitle.vue')['default']
    Suggestion: typeof import('./../components/Suggestion.vue')['default']
    TabHome: typeof import('./../components/TabHome.vue')['default']
    Time: typeof import('./../components/Time.vue')['default']
    UniqueId: typeof import('./../components/tools/generate/module/uniqueId.vue')['default']
    Uuid: typeof import('./../components/tools/generate/module/uuid.vue')['default']
    Var: typeof import('./../components/tools/convert/module/var.vue')['default']
  }
}
