/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackGround: typeof import('./../components/module/BackGround.vue')['default']
    Base64: typeof import('./../components/tools/convert/Base64.vue')['default']
    Bookmark: typeof import('./../components/TabModule/Bookmark.vue')['default']
    Color: typeof import('./../components/tools/generate/Color.vue')['default']
    DateTime: typeof import('./../components/TabModule/DateTime.vue')['default']
    Expand: typeof import('./../components/Expand.vue')['default']
    Hash: typeof import('./../components/tools/convert/Hash.vue')['default']
    Math: typeof import('./../components/tools/convert/Math.vue')['default']
    Search: typeof import('./../components/TabModule/Search.vue')['default']
    SearchIcon: typeof import('./../components/module/SearchIcon.vue')['default']
    SettingModal: typeof import('./../components/module/SettingModal.vue')['default']
    Suggestion: typeof import('./../components/TabModule/Suggestion.vue')['default']
    TabHome: typeof import('./../components/TabHome.vue')['default']
    Time: typeof import('./../components/tools/convert/Time.vue')['default']
    ToolsList: typeof import('./../components/tools/ToolsList.vue')['default']
    ToolsView: typeof import('./../components/tools/ToolsView.vue')['default']
    UniqueId: typeof import('./../components/tools/generate/UniqueId.vue')['default']
    Uuid: typeof import('./../components/tools/generate/Uuid.vue')['default']
    Var: typeof import('./../components/tools/convert/Var.vue')['default']
  }
}
